#!/usr/bin/env python3
"""Extract and minify landing-page critical CSS from style.css."""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
STYLE = ROOT / "css" / "style.css"
OUT = ROOT / "css" / "landing-critical.css"
OUT_MIN = ROOT / "css" / "landing-critical.min.css"

RANGES = [
    (1, 129),
    (1753, 1788),
    (1918, 1921),
    (1923, 1976),
    (2067, 2327),
    (2871, 3459),
    (4103, 4509),
]


def minify_css(text: str) -> str:
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)
    text = re.sub(r"\s+", " ", text)
    text = re.sub(r"\s*([{}:;,>+~])\s*", r"\1", text)
    text = text.replace(";}", "}")
    return text.strip()


lines = STYLE.read_text(encoding="utf-8").splitlines()
chunks: list[str] = []
for start, end in RANGES:
    chunks.append("\n".join(lines[start - 1 : end]))

header = (
    "/* Auto-generated by scripts/build_landing_critical_css.py — do not edit manually */\n"
    "/* Landing critical path: layout, header, footer, project cards */\n\n"
)
full = header + "\n\n".join(chunks) + "\n"
OUT.write_text(full, encoding="utf-8")
OUT_MIN.write_text(minify_css(full), encoding="utf-8")
print(f"Wrote {OUT} ({OUT.stat().st_size} bytes)")
print(f"Wrote {OUT_MIN} ({OUT_MIN.stat().st_size} bytes)")
